name: 'PR compliance action'
description: 'Check authors and title/description of a PR'
author: 'GoodData'
inputs:
  special-authors:
    required: false
    description: 'The PR is compliant if all commits of the PR are authored by special-authors'
  special-title-regexes:
    required: false
    description: ''
  required-ticket-regex:
    required: false
    description: 'Regular expression of a string that should be mentioned in PR title or PR description'
runs:
  using: 'node16'
  main: 'dist/index.js'
