name: 'PR compliance action'
description: 'Check authors and title/description of a PR'
author: 'GoodData'
inputs:
  token:
    required: true
    description: "Token to query GitHub API. It needs to have pull-request:read permission"
    default: ${{ github.token }}
  special-authors:
    required: false
    description: 'The PR is compliant if all commits of the PR are authored by special-authors'
  special-title-regexes:
    required: false
    description: 'The PR is compliant if title or description contains matches one of these regular expressions'
  required-ticket-regex:
    required: false
    description: 'PR title or description must match this regular expression'
runs:
  using: 'node16'
  main: 'dist/index.js'
